version: "3.8"

services:
  api:
    container_name: flask_api
    build:
      context: .
      dockerfile: docker_files/Dockerfile
    command: flask --debug run --host 0.0.0.0 --port 8080
    environment:
      - FLASK_APP=/flask_app/src/app
    volumes:
      - ./src:/src
    ports:
      - "8080:8080"

