version: "3.8"

services:
  api:
    container_name: flask_api
    build:
      context: .
      dockerfile: docker_files/Dockerfile
    environment:
      - FLASK_APP=/flask_app/src
    volumes:
      - ./:/flask_app/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: sw_db

